export const Routes = {
  Signup: "/signup",
  Verify: "/signup/verification",
  Login: "/login",
  ProviderDashboard: "/dashboard",
  ProviderReminders: "/dashboard/reminders",
  ProviderPatients: "/dashboard/patients",
  ProviderMessages: "/dashboard/messages",
  ProviderReports: "/dashboard/reports",
  ProviderStatistics: "/dashboard/statistics",
  PatientDashboard: "/patient/dashboard",
  PatientMedications: "/patient/dashboard/medications",
  PatientReminders: "/patient/dashboard/reminders",
  PatientReport: "/patient/dashboard/report",
  LandingPage: "/landing",
};
